export const JOBS = {
  SCAN_SUPPLIER: "SCAN_SUPPLIER",
  SCAN_MARKETPLACE_PRICE: "SCAN_MARKETPLACE_PRICE",
  MATCH_PRODUCT: "MATCH_PRODUCT",
  EVAL_PROFIT: "EVAL_PROFIT",
  CREATE_LISTING: "CREATE_LISTING",
  ORDER_SYNC: "ORDER_SYNC",
} as const;

export type JobName = (typeof JOBS)[keyof typeof JOBS];
