import type { OrderStatus } from "./statuses";

const ORDER_STATUS_TRANSITIONS: Readonly<Record<OrderStatus, readonly OrderStatus[]>> = {
  NEW: ["MANUAL_REVIEW", "NEW_ORDER", "READY_FOR_PURCHASE_REVIEW"],
  SYNCED: ["MANUAL_REVIEW", "NEW_ORDER", "READY_FOR_PURCHASE_REVIEW"],
  PURCHASE_PENDING: ["PURCHASE_APPROVED", "FAILED", "CANCELED"],
  PURCHASED: ["TRACKING_PENDING", "TRACKING_RECEIVED", "TRACKING_SYNCED"],
  PARTIALLY_PURCHASED: ["TRACKING_PENDING", "TRACKING_RECEIVED", "TRACKING_SYNCED"],
  SHIPPED: ["DELIVERED", "TRACKING_SYNCED"],
  DELIVERED: [],
  CANCELED: [],
  FAILED: ["MANUAL_REVIEW", "READY_FOR_PURCHASE_REVIEW"],
  MANUAL_REVIEW: ["NEW_ORDER", "READY_FOR_PURCHASE_REVIEW", "FAILED", "CANCELED"],
  NEW_ORDER: ["READY_FOR_PURCHASE_REVIEW", "FAILED", "CANCELED"],
  READY_FOR_PURCHASE_REVIEW: ["PURCHASE_APPROVED", "FAILED", "CANCELED"],
  PURCHASE_APPROVED: ["PURCHASE_PLACED", "PURCHASE_PENDING", "FAILED", "CANCELED"],
  PURCHASE_PLACED: ["TRACKING_PENDING", "TRACKING_RECEIVED", "FAILED", "CANCELED"],
  TRACKING_PENDING: ["TRACKING_RECEIVED", "TRACKING_SYNCED", "FAILED", "CANCELED"],
  TRACKING_RECEIVED: ["TRACKING_SYNCED", "FAILED", "CANCELED"],
  TRACKING_SYNCED: ["DELIVERED", "FAILED", "CANCELED"],
};

export function getAllowedNextOrderStatuses(current: OrderStatus): readonly OrderStatus[] {
  return ORDER_STATUS_TRANSITIONS[current] ?? [];
}

export function canTransitionOrderStatus(current: OrderStatus, next: OrderStatus): boolean {
  if (current === next) return true;
  return getAllowedNextOrderStatuses(current).includes(next);
}
