import { ORDER_STATUS, type OrderStatus } from "./statuses";

const ORDER_STATUS_TRANSITIONS: Readonly<Record<OrderStatus, readonly OrderStatus[]>> = {
  NEW: [ORDER_STATUS.MANUAL_REVIEW, ORDER_STATUS.NEW_ORDER, ORDER_STATUS.READY_FOR_PURCHASE_REVIEW],
  SYNCED: [ORDER_STATUS.MANUAL_REVIEW, ORDER_STATUS.NEW_ORDER, ORDER_STATUS.READY_FOR_PURCHASE_REVIEW],
  PURCHASE_PENDING: [ORDER_STATUS.PURCHASE_APPROVED, ORDER_STATUS.FAILED, ORDER_STATUS.CANCELED],
  PURCHASED: [ORDER_STATUS.TRACKING_PENDING, ORDER_STATUS.TRACKING_RECEIVED, ORDER_STATUS.TRACKING_SYNCED],
  PARTIALLY_PURCHASED: [ORDER_STATUS.TRACKING_PENDING, ORDER_STATUS.TRACKING_RECEIVED, ORDER_STATUS.TRACKING_SYNCED],
  SHIPPED: [ORDER_STATUS.DELIVERED, ORDER_STATUS.TRACKING_SYNCED],
  DELIVERED: [],
  CANCELED: [],
  FAILED: [ORDER_STATUS.MANUAL_REVIEW, ORDER_STATUS.READY_FOR_PURCHASE_REVIEW],
  MANUAL_REVIEW: [ORDER_STATUS.NEW_ORDER, ORDER_STATUS.READY_FOR_PURCHASE_REVIEW, ORDER_STATUS.FAILED, ORDER_STATUS.CANCELED],
  NEW_ORDER: [ORDER_STATUS.READY_FOR_PURCHASE_REVIEW, ORDER_STATUS.FAILED, ORDER_STATUS.CANCELED],
  READY_FOR_PURCHASE_REVIEW: [ORDER_STATUS.PURCHASE_APPROVED, ORDER_STATUS.FAILED, ORDER_STATUS.CANCELED],
  PURCHASE_APPROVED: [ORDER_STATUS.PURCHASE_PLACED, ORDER_STATUS.PURCHASE_PENDING, ORDER_STATUS.FAILED, ORDER_STATUS.CANCELED],
  PURCHASE_PLACED: [ORDER_STATUS.TRACKING_PENDING, ORDER_STATUS.TRACKING_RECEIVED, ORDER_STATUS.FAILED, ORDER_STATUS.CANCELED],
  TRACKING_PENDING: [ORDER_STATUS.TRACKING_RECEIVED, ORDER_STATUS.TRACKING_SYNCED, ORDER_STATUS.FAILED, ORDER_STATUS.CANCELED],
  TRACKING_RECEIVED: [ORDER_STATUS.TRACKING_SYNCED, ORDER_STATUS.FAILED, ORDER_STATUS.CANCELED],
  TRACKING_SYNCED: [ORDER_STATUS.DELIVERED, ORDER_STATUS.FAILED, ORDER_STATUS.CANCELED],
};

export const ORDER_PURCHASE_RECORDABLE_STATUSES = [
  ORDER_STATUS.PURCHASE_APPROVED,
  ORDER_STATUS.PURCHASE_PLACED,
  ORDER_STATUS.TRACKING_PENDING,
  ORDER_STATUS.TRACKING_RECEIVED,
  ORDER_STATUS.TRACKING_SYNCED,
] as const satisfies readonly OrderStatus[];

export const ORDER_TRACKING_RECORDABLE_STATUSES = [
  ORDER_STATUS.PURCHASE_PLACED,
  ORDER_STATUS.TRACKING_PENDING,
  ORDER_STATUS.TRACKING_RECEIVED,
  ORDER_STATUS.TRACKING_SYNCED,
] as const satisfies readonly OrderStatus[];

export function getAllowedNextOrderStatuses(current: OrderStatus): readonly OrderStatus[] {
  return ORDER_STATUS_TRANSITIONS[current] ?? [];
}

export function canTransitionOrderStatus(current: OrderStatus, next: OrderStatus): boolean {
  if (current === next) return true;
  return getAllowedNextOrderStatuses(current).includes(next);
}

export function canRecordSupplierPurchaseForOrderStatus(status: OrderStatus): boolean {
  return (ORDER_PURCHASE_RECORDABLE_STATUSES as readonly OrderStatus[]).includes(status);
}

export function canRecordTrackingForOrderStatus(status: OrderStatus): boolean {
  return (ORDER_TRACKING_RECORDABLE_STATUSES as readonly OrderStatus[]).includes(status);
}
